### ISSUE TITLE
Blocker missing ProductAttributeMetadata in 0.0.1

### ISSUE THREAD

**Issue by larsroettig** [magento/magento2-pwa#1]
Pls, release a new version of this meta packed because.
Lasted release from PWAStudio required already `ProductAttributeMetadata` in but this is not available in 0.0.1
`@magento/peregrine/lib/talons/RootComponents/Product/productDetailFragment.gql.js`

**Comment by devpatil7** [comment]
@larsroettig I do see in repo.magento.com `magento-pwa-0.1.0 (Internal, External)` , I'm able to fetch it with following - 

```
  "require": {
    "magento/composer-root-update-plugin": "~1.1",
    "magento/magento-cloud-metapackage": ">=2.4.3 <2.4.4",
    "magento/module-upward-connector": "2.0.0",
    "magento/pwa": "0.1.0"
```

**Comment by devpatil7** [comment]
@larsroettig I did add missing tag as well https://github.com/magento-commerce/magento2-pwa/tree/0.1.0 but this public repo is not synced. I will keep you posted.

**Comment by brijeshbha** [comment]
Any update on this? I am getting 404 error on Product page. :(

**Comment by anthoula** [comment]
@magento export issue to JIRA project PWA as Bug
