### ISSUE TITLE
No results returned when Category filter is applied.

### ISSUE THREAD

**Issue by mekoahdd** [magento/magento2-pwa#11]
Hi Magento-PWA team.

We are using:

Pwa studio 12.0.6
Venia 9.0
Magento Backend 2.4.5

This commit [8b1e5d7e5e41db210b78a5bd9832053c09bb2493](https://github.com/magento/magento2-pwa/commit/8b1e5d7e5e41db210b78a5bd9832053c09bb2493) has caused an error since that file that converts the ids of the categories to uids is necessary for the correct operation of the search in the versions we are using.

I momentarily replicated the removed code so that my search doesn't have problems.

I would like to know if I am doing something wrong? or why this file was deleted?

Thank you !

**Comment by glo42707** [comment]
closing this issue as https://jira.corp.adobe.com/browse/PWA-3066 is alredy fixed and deployed on PWA-13.1.0
