### ISSUE TITLE
errors error on PWA frontend

### ISSUE THREAD

**Issue by nix0x00** [magento/magento2-pwa#8]
hi, I installed this module as I read for PWA metapackage was necessary for PWA versions later than 12.1.0. 
But I am still getting error on the PWA frontend i.e.

`Cannot query field "errors" on type "CartItemInterface".`

I think errors dosn't exist on type CartItemInterface, and this metapackage is installed. 

Need help here.

**Comment by anthoula** [comment]
Thank you for the feedback. The current compatibility matrix is [found here](https://developer.adobe.com/commerce/pwa-studio/integrations/adobe-commerce/version-compatibility/). If issue still occurs with current compatible modules, please reopen as a Bug.
